### ISSUE TITLE
F64FlatArray::copy should return F64FlatArray

### ISSUE THREAD

**Issue by altavir** [JetBrains-Research/viktor#29]
I am not sure it is a frequent use-case, but it costs nothing to override the method.

**Comment by dievsky** [comment]
I was actually thinking of hiding the type hierarchy completely, leaving only the base `F64Array` class public, since the implementation specifics aren't really relevant for the user.

**Comment by dievsky** [comment]
Summary: just two types are now public, `F64Array` and `F64FlatArray`. `copy()` returns the correct type. Other types are now internal. Will close after the release.

**Comment by dievsky** [comment]
Resolved in the release candidate 1.1.0-rc-1.
