### ISSUE TITLE
Specify JVM in benchmarks

### ISSUE THREAD

**Issue by altavir** [JetBrains-Research/viktor#31]
OpenJDK has internal SIMD starting with 10 or 11, so the test results could be quite different for different VMs. Also makes sense to test with GraalVM. It has both SIMD and better escape analysis and inlining.

**Comment by dievsky** [comment]
Yes, this looks like an oversight. I'll add the JVM version.

**Comment by dievsky** [comment]
JVM versions used in benchmarks were specified.

GraalVM and later OpenJDK testing warrants a separate issue.
