### ISSUE TITLE
Provide reduce method

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/viktor#41]
It would be nice to have a general reduction method.

**Comment by Jolanrensen** [comment]
So, something like this?

```kotlin
inline fun F64FlatArray.reduce(operation: (acc: Double, Double) -> Double): Double {
    if (size == 0) throw UnsupportedOperationException("Empty array can't be reduced.")

    var accumulator = this[0]
    var i = 1
    while (i < size) {
        accumulator = operation(accumulator, this[i++])
    }
    return accumulator
}
```

**Comment by dievsky** [comment]
Exactly like this, but with an initial value and specialized for dense arrays.

**Comment by Jolanrensen** [comment]
With initial value? That's not reduce, that's fold, right?

**Comment by dievsky** [comment]
Yep, my terminology was incorrect. Now that I've got it in check, I can say I prefer `fold` to `reduce`, since it's a bit cleaner.

**Comment by Jolanrensen** [comment]
Reduce is also very useful though. It's just that the initial value then is the first item in the collection. So having them both would be best probably :)

**Comment by dievsky** [comment]
Frankly, I seem hard-pressed to think of a use-case where `reduce` can't be readily expressed as `fold`. Can you give me an example?

**Comment by Jolanrensen** [comment]
You can but it might not make much sense to do it. For instance reducing by sum. You could do it with a fold that starts at 0, but you'd have to add the 0 somewhere whereas with a reduce it wouldn't. Same with a reduce by product, having to start off with a 1. Simply having a reduce and fold (like in the kotlin standard library) I think is the best option.
